# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MachineId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, instance_id: str=None):  # noqa: E501
        """MachineId - a model defined in Swagger

        :param instance_id: The instance_id of this MachineId.  # noqa: E501
        :type instance_id: str
        """
        self.swagger_types = {
            'instance_id': str
        }

        self.attribute_map = {
            'instance_id': 'instanceId'
        }

        self._instance_id = instance_id

    @classmethod
    def from_dict(cls, dikt) -> 'MachineId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineId of this MachineId.  # noqa: E501
        :rtype: MachineId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def instance_id(self) -> str:
        """Gets the instance_id of this MachineId.


        :return: The instance_id of this MachineId.
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id: str):
        """Sets the instance_id of this MachineId.


        :param instance_id: The instance_id of this MachineId.
        :type instance_id: str
        """
        if instance_id is None:
            raise ValueError("Invalid value for `instance_id`, must not be `None`")  # noqa: E501

        self._instance_id = instance_id
